import { AnnotationConfig } from '../../components/ProductAnnotation'

export const supplierManagementAnnotations: AnnotationConfig = {
  pageName: '供应商管理',
  version: '1.0.0',
  lastUpdated: '2026-07-14',
  annotations: [
    {
      id: 'anno-001',
      target: 'alert-data-source',
      type: 'data',
      title: '数据来源说明',
      description: '页面顶部 Alert 提示供应商数据的来源和同步方式。',
      details: {
        dataSource: '供应商管理平台（智引系统）',
        fields: [
          { name: 'supplier_code', type: 'string', description: '供应商编码，由智引系统分配' },
          { name: 'supplier_name', type: 'string', description: '供应商名称' },
          { name: 'auth_status', type: 'string', description: '认证状态：已认证/认证中/未认证' },
        ],
      },
    },
    {
      id: 'anno-002',
      target: 'search-filter',
      type: 'function',
      title: '高级搜索筛选',
      description: 'AdvancedSearchFilter 组件，支持多条件组合筛选供应商列表。',
      details: {
        functionName: '供应商搜索筛选',
        entryPath: '/suppliers 页面顶部搜索区',
        priority: 'P1',
      },
      communicationNote: '2026-07-14 沟通：已移除「品类归属」搜索筛选项；已合并供应商编码与名称为一个搜索字段（支持编码或名称模糊匹配）；已去掉认证状态筛选项',
    },
    {
      id: 'anno-003',
      target: 'supplier-table',
      type: 'function',
      title: '供应商列表',
      description: '展示供应商基础信息列表，支持分页、排序、固定列。当前展示 3 条 Mock 数据。',
      details: {
        functionName: '供应商列表展示',
        entryPath: '/suppliers 页面主体表格',
        priority: 'P0',
      },
      communicationNote: '2026-07-14 沟通：已移除「品类归属」列、「创建方式」列；scroll.x 从 1800 调整为 1700',
    },
    {
      id: 'anno-004',
      target: 'col-auth-status',
      type: 'business',
      title: '认证状态',
      description: '供应商的认证状态，影响登录和操作权限。',
      details: {
        businessRule: '认证状态由智引系统同步，零售商端不可修改',
        statusFlow: ['未认证', '认证中', '已认证'],
        permission: '所有角色可查看，不可编辑',
      },
    },
    {
      id: 'anno-005',
      target: 'col-login-status',
      type: 'business',
      title: '登录状态管理',
      description: '供应商的登录状态，控制供应商端系统访问权限。',
      details: {
        businessRule: '登录状态根据供应商认证状态和配置情况自动计算',
        statusFlow: ['正常', '异常', '临时开通'],
        permission: '系统管理员可查看和修改',
      },
    },
    {
      id: 'anno-006',
      target: 'btn-user-manage',
      type: 'interaction',
      title: '用户管理入口',
      description: '点击「用户管理」按钮打开 Drawer，展示该供应商下的用户列表。',
      details: {
        trigger: '点击「用户管理」按钮',
        feedback: '右侧滑出 Drawer，展示用户列表',
        stateChange: 'userManageVisible → true',
        exceptionHandling: '若供应商无用户，显示空状态提示',
      },
    },
    {
      id: 'anno-007',
      target: 'btn-config-admin',
      type: 'interaction',
      title: '配置管理员入口',
      description: '仅在供应商未配置管理员时显示，点击打开配置弹窗。',
      details: {
        trigger: '点击「配置管理员」按钮（条件渲染：!record.has_config_person）',
        feedback: '弹出管理员配置 Modal',
        stateChange: 'configVisible → true',
        exceptionHandling: '已配置管理员的供应商不显示此按钮',
      },
    },
    {
      id: 'anno-008',
      target: 'drawer-user-manage',
      type: 'function',
      title: '用户管理抽屉',
      description: '展示供应商下的用户列表，包含用户姓名、手机号、角色、状态等信息，支持查看用户详情和授权委托书。',
      details: {
        functionName: '用户管理',
        entryPath: '/suppliers → 点击「用户管理」',
        priority: 'P0',
      },
      communicationNote: '2026-07-14 沟通：用户列表已删除「数据权限范围」列；角色列改为多角色 Tag 展示（role_names 数组渲染）；已增加分页（pageSize 10，showSizeChanger）',
    },
    {
      id: 'anno-009',
      target: 'drawer-user-detail',
      type: 'function',
      title: '用户详情抽屉',
      description: '展示用户基本信息、登录记录、操作日志，支持修改超管和查看授权委托书。',
      details: {
        functionName: '用户详情查看',
        entryPath: '用户管理 Drawer → 点击用户行',
        priority: 'P1',
      },
      communicationNote: '2026-07-14 沟通：基本信息已删除「角色」「角色类型」两项；「最近操作记录」卡片改为「登录记录」，字段改为登录时间、登录方式/IP、登录结果、IP地址；mock 数据 recent_operations 改为 login_records',
    },
    {
      id: 'anno-010',
      target: 'btn-change-admin',
      type: 'interaction',
      title: '修改超管',
      description: '点击打开修改超管弹窗，填写新手机号/姓名/邮箱后直接提交。',
      details: {
        trigger: '在用户详情中点击「修改超管」',
        feedback: '弹出 ChangeSuperAdminModal',
        stateChange: 'changeAdminVisible → true',
        exceptionHandling: '提交时校验手机号格式（11位、1开头、第二位3-9）',
      },
      communicationNote: '2026-07-14 沟通：已移除验证码流程，修改超管无需再次发送验证码，直接填写手机号/姓名/邮箱提交',
    },
    {
      id: 'anno-011',
      target: 'drawer-esign-auth',
      type: 'function',
      title: '授权委托书查看',
      description: '展示用户的电子签章授权委托书信息，包含提交时间、状态、授权编号、有效期等。',
      details: {
        functionName: '授权委托书管理',
        entryPath: '用户详情 → 点击「授权委托书」',
        priority: 'P1',
      },
    },
    {
      id: 'anno-012',
      target: 'esign-auth-view',
      type: 'business',
      title: '授权委托书查看权限',
      description: '零售商端根据供应商上传的文件显示查看权限。供应商未上传文件时提示等待上传。',
      details: {
        businessRule: '只有当 esign_auth.file_url 存在时才显示「查看授权书」按钮',
        validation: 'file_url 非空时启用查看，为空时显示 Alert 提示「供应商尚未上传授权委托书文件」',
        permission: '零售商管理员可查看供应商上传的授权委托书',
      },
      communicationNote: '2026-07-14 沟通：零售商端需要根据供应商上传的文件，拥有查看此委托书权限才行',
    },
    {
      id: 'anno-013',
      target: 'esign-auth-approval',
      type: 'business',
      title: '授权委托书审批流程',
      description: '授权委托书的状态流转和审批操作。',
      details: {
        businessRule: '待审核状态可执行通过/驳回操作；已驳回状态可执行重新通过操作',
        statusFlow: ['未提交(none)', '待审核(pending)', '已通过(approved)', '已驳回(rejected)'],
        permission: '零售商管理员可审批',
        validation: '驳回时必须填写驳回原因',
      },
      communicationNote: '2026-07-14 沟通：供应商端被驳回后能看到驳回原因并修改重新提交；新建独立的 /esign-approval 内部审批页面，承接供应商端提交的授权书申请，支持通过/驳回/重新通过操作',
    },
    {
      id: 'anno-014',
      target: 'btn-batch-import',
      type: 'interaction',
      title: '批量导入超管',
      description: '点击打开批量导入 Modal，支持模板下载、文件上传、进度展示和结果查看。',
      details: {
        trigger: '点击「超管导入」按钮',
        feedback: '弹出批量导入 Modal，包含步骤条、说明区、模板下载、文件上传区域',
        stateChange: 'batchImportVisible → true',
        exceptionHandling: '文件格式校验（仅 .xlsx/.xls）、文件大小校验（<10MB）',
      },
      communicationNote: '2026-07-14 沟通：已移除 Modal 标题图标、footer 按钮图标、Alert showIcon',
    },
    {
      id: 'anno-015',
      target: 'batch-import-template',
      type: 'data',
      title: '导入模板字段',
      description: 'Excel 模板包含供应商编码和超管手机号两个字段，均为必填。',
      details: {
        dataSource: '前端生成 Excel 模板（handleDownloadTemplate）',
        fields: [
          { name: 'supplier_code', type: 'string', description: '供应商编码（必填），须已存在于供应商列表中' },
          { name: 'phone', type: 'string', description: '超管手机号（必填），11位数字，1开头第二位3-9' },
        ],
      },
      communicationNote: '2026-07-14 沟通：已移除「备注」字段，模板仅包含供应商编码和超管手机号',
    },
    {
      id: 'anno-016',
      target: 'operation-logs',
      type: 'data',
      title: '操作日志',
      description: '记录用户管理相关操作，包含操作类型、操作人、操作时间、变更详情等。',
      details: {
        dataSource: '前端 Mock 数据（generateMockOperationLogs）',
        apiEndpoint: '未来对接 /api/operation-logs（当前为 Mock）',
        fields: [
          { name: 'operation_type', type: 'string', description: '操作类型：change_phone/config_admin/batch_import' },
          { name: 'operator_name', type: 'string', description: '操作人姓名' },
          { name: 'operation_time', type: 'datetime', description: '操作时间' },
          { name: 'change_detail', type: 'object', description: '变更详情：field/old_value/new_value' },
          { name: 'result', type: 'string', description: '操作结果：success/failed' },
        ],
      },
    },
    {
      id: 'anno-017',
      target: 'table-action-col',
      type: 'interaction',
      title: '表格操作列',
      description: '操作列根据供应商状态动态显示按钮，固定在表格右侧。',
      details: {
        trigger: '页面加载时根据供应商数据动态渲染操作按钮',
        feedback: '显示「用户管理」按钮；未配置管理员时额外显示「配置管理员」按钮',
        stateChange: '点击不同按钮触发对应的 Drawer/Modal',
        exceptionHandling: '已配置管理员的供应商仅显示「用户管理」',
      },
      communicationNote: '2026-07-14 沟通：已移除所有操作按钮的 antd 图标（icon 属性）',
    },
  ],
}
